//! I/Oを持たないドメインの型と純粋関数。テストを速く確実にするため、ここには副作用を置かない。
pub mod activity;
pub mod backoff;
pub mod calendar;
pub mod catalog;
pub mod display;
pub mod live_log;
pub mod memory;
pub mod memory_text;
pub mod pricing;
pub mod profile;
pub mod projection;
pub mod read_models;
pub mod records;
pub mod session_id;
pub mod session_summary;
pub mod settings;
pub mod transcript;
pub mod usage;
